title: Anrich Tait

tagline: New Website Coming Soon

logo:

description: "Temporary site while working on something new. Check out the blog archive for previous posts."

# The base hostname & protocol of your site for where absolute urls are needed
url: https://anrichtait.github.io

# The subpath of your site, if you want to host your path on a subpath like on GitHub Pages. e.g. /blog
baseurl: ""

sass:
  sass_dir: _sass

# Site navigation - disabled for minimal site
# navigation:


# Author information - author info at the bottom of the post
author_name: "Anrich Tait"
author_bio: "Hi there, I'm Anrich Tait. I like to work out, learn deeply, and live fully—sharing the journey of strength, growth, and everyday discipline"
author_url: "https://www.instagram.com/anrichtait/"

# Social links in the site footer
twitter_username: ""
facebook_username: ""
github_username: "anrichtait"
codepen_username: ""
dribbble_username: ""
medium_username: ""
instagram_username: "anrichtait"
pinterest_username: ""
linkedin_username: ""

# Jekyll plugins
plugins: [jekyll-paginate]

permalink: pretty
markdown: kramdown
kramdown:
    auto_ids: false
